name: tda_adni_mlcb
channels:
  - bioconda
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipython
  - pandas
  - scikit-learn
  - argparse
  - pathlib
  - python-dotenv
  - pip
  - pip:
      - giotto-tda
      - scikit-tda
      - nilearn
      - python-dotenv
